In [11]:
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1])
a[0]=5
print(a)

b=np.zeros((2,2))
c=np.ones((1,2))
d=np.full((2,2),7)
e=np.eye(4)
f=np.random.random((2,2))
print(b)
print(c)
print(d)
print(e)
print(f)
print('*'*40)


<class 'numpy.ndarray'>
(3,)
1 2
[5 2 3]
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.18560637 0.68886284]
 [0.01584835 0.55641323]] /n


In [21]:
import numpy as np
#slice
a=np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.dtype)
b=a[:2,1:3]
print(b)
print(a[0,1])
b[0,0]=777
#b[0,0] is same as a[0,1]
print(a[0,1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
4
15
int32
[[1 2]
 [6 7]]
1
777


In [34]:
import numpy as np
#slice indexing
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("a= \n",a,"\n")

row_r1=a[1,:]
row_r2=a[1:2,:]
print(row_r1)
print(row_r2)

col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1)
print(col_r2)

#indexing
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,1],a[0,1]]))


a= 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[5 6 7 8]
[[5 6 7 8]]
[ 2  6 10]
[[ 2]
 [ 6]
 [10]]
[1 6 9]
[2 2]


In [2]:
#int array indexing
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=np.array([0,2,0,1]) #array of indices created
print(a)
print(a[np.arange(4),b]) #arrange array of indices
a[np.arange(4),b]+=10 #mutate one element from each row of a using indices in b
print(a)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [7]:
#bool array indexing
import numpy as np
a=np.arange(6).reshape(3,2)
print(a)
bool_ids=(a>2)
print(bool_ids)
print(a[bool_ids])
print(a[a>2])

[[0 1]
 [2 3]
 [4 5]]
[[False False]
 [False  True]
 [ True  True]]
[3 4 5]
[3 4 5]


In [2]:
#data types
import numpy as np
b=np.array([1.0,2.0])
print(b.dtype)
a=np.array([[1,2],[3,4]])
print(a.dtype)

print(a+a)
print(np.add(a,a))
print(a-a)
print(np.subtract(a,a))
print(a*a)
print(np.multiply(a,a)) # elementary multiplication
print(a/a)
print(np.divide(a,a))
print(np.sqrt(a))
#vector multiplication
print(a.dot(a))
x=np.array([[1,2],[3,4]])
y=np.array([5,6])
print(x.dot(y))
print(y.dot(x))
print(np.matmul(x,y)) #same as dot command

#transpose
print(a.T)
print(y.T) #does nothing for 1 row arrays


float64
int32
[[2 4]
 [6 8]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 7 10]
 [15 22]]
[17 39]
[23 34]
[17 39]
[[1 3]
 [2 4]]
[5 6]


In [10]:
#stats
import numpy as np
x = np.array([23, 40, 6, 74, 38, 1, 70])
print(np.mean(x))
print(np.median(x))
print(np.std(x))

36.0
38.0
26.49528259898354
